---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prep-rpm-source
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: konflux
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |-
    Prepare RPM source for SAST scanning.
  params:
    - name: SNAPSHOT
      description: The JSON string of the Snapshot produced by the build pipeline
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
  results:
    - name: PREPARED_SOURCE_ARTIFACT
      description: Trusted artifact with prepared RPM source code.
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    # based on https://github.com/konflux-ci/integration-examples/blob/main/tasks/test_metadata.yaml
    - name: parse-snapshot
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:43d997ac61bef77eaee0413fe50c29b66eb4d0d32066f5bd4a83f39e4b2d9457
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
      results:
        - name: OCI_STORAGE
          description: |
            OCI registry URL where the pipeline stores trusted artifacts, including
            both resulting artifacts and intermediary by-products.
        - name: DEPENDENCIES_ARTIFACT
          description: repo:digest of rpm-sources'  "dependencies-artifact" produced in the build
      script: |
        #!/usr/bin/env bash

        set -euo pipefail
        set -x

        echo "${SNAPSHOT}"

        SOURCE_GIT_REVISION=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .source.git.revision' <<< "${SNAPSHOT}")
        COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")

        # Use tag convention of <repo>:<commit>.rpm-sources
        # to identify source code artifact. This makes many assumptions, it may
        # be better to find another approach e.g. extract from slsa attestation
        REPO="${COMPONENT_CONTAINER_IMAGE%@*}"
        OCI_STORAGE="${REPO}:${SOURCE_GIT_REVISION}"
        RPM_SOURCES_IMAGE="${OCI_STORAGE}.rpm-sources"
        MANIFEST=$(oras manifest get "${RPM_SOURCES_IMAGE}")
        DIGEST=$(echo -n "$MANIFEST" | jq -r \
                  '.layers[] | select( .annotations["org.opencontainers.image.title"] == "dependencies-artifact") | .digest')

        # example results:
        # <repo>:<commit>
        # <repo>@<digest> of "dependencies-artifact" blob in <repo>:<commit>.rpm-sources image
        echo -n "${OCI_STORAGE}" > "$(step.results.OCI_STORAGE.path)"
        echo -n "${REPO}@${DIGEST}" > "$(step.results.DEPENDENCIES_ARTIFACT.path)"

    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:43d997ac61bef77eaee0413fe50c29b66eb4d0d32066f5bd4a83f39e4b2d9457
      args:
        - use
        - oci:$(steps.parse-snapshot.results.DEPENDENCIES_ARTIFACT)=/var/workdir/source
      env:
        - name: DEBUG
          value: "1"
      volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
    - name: prep-rpm-source
      # this is a custom image based on the upstream image:
      # https://github.com/konflux-ci/rpmbuild-pipeline-environment-container/tree/main
      # downstream environment image contains extras like brewkoji config
      # TODO - add rpmbuild to environment image?
      image: quay.io/sfowler/rpmbuild-environment:latest
      imagePullPolicy: Always
      workingDir: /var/workdir/source
      script: |
        #!/usr/bin/env bash

        set -euo pipefail
        set -x

        # prepare RPM source, extract archives and apply patches
        rpmbuild --bp --nodeps ./*.spec --define '_topdir /var/workdir/build' --define "_sourcedir $(pwd)"
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          # if successful BUILD directory will contain ready source
          builddir=$(find /var/workdir/build/BUILD -maxdepth 1 -mindepth 1 -type d)
          echo "INFO: source prepared in $builddir"
          # echo "$builddir" > $(results.PREPARED_SOURCE_ARTIFACT.path)
        else
          echo "ERROR: source prep with 'rpmbuild -bp --nodeps' failed"
          # TODO: fallback, simple extraction of archives, maybe use /usr/lib/rpm/rpmuncompress
          exit 1
        fi
    - name: create-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:43d997ac61bef77eaee0413fe50c29b66eb4d0d32066f5bd4a83f39e4b2d9457
      args:
        - create
        - --store
        - $(step.results.IMAGE_REPO.path)
        - $(results.PREPARED_SOURCE_ARTIFACT.path)=/var/workdir/build/BUILD
  volumes:
    - name: trusted-ca
      configMap:
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        name: $(params.caTrustConfigMapName)
        optional: true
    - name: workdir
      emptyDir: {}
