# yamllint disable-file

# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
# Please consider sending a PR upstream instead of editing the file directly.
# See the SHARED-CI.md document in this repo for more details.

name: Check task migrations
"on":
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          cluster_name: kind
      - uses: tektoncd/actions/setup-tektoncd@main
        with:
          pipeline_version: v1.12.2
      - name: Run check
        run: |
          DEBIAN_FRONTEND=noninteractive \
          sudo apt-get install -y --no-install-recommends \
              tzdata python3-ruamel.yaml

          kubectl get all -n tekton-pipelines
          # Require name main
          git branch main origin/main
          # Make `git branch --show-current` works.
          git checkout -b pr-verify
          export IN_CLUSTER=1
          bash ./hack/validate-migration.sh
