name: Validate PR - check task owners
'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  check:
    name: Check Task OWNERS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check task owners
        run: |
          ./hack/check-task-owners.sh

      - name: Check task version labels
        run: |
          ./hack/check-task-version-labels.sh
