name: Validate PR - Trusted Artifact variants
'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  go:
    name: Check Trusted Artifact variants
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check Trusted Artifact variants
        id: check
        run: hack/generate-ta-tasks.sh
        uses: actions/upload-artifact@v4
        with:
          name: Trusted artifacts patch
          path: ./ta.patch
